app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Optional


class SearchForm(FlaskForm):
    phrase = StringField('Phrase', validators=[DataRequired()])
    from_ = DateField('From', validators=[Optional()])
    to = DateField('To', validators=[Optional()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap

from config import Config
import xapian

db = xapian.Database(Config.XAPIAN_DATABASE, xapian.DB_OPEN)
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import json
from datetime import datetime

import xapian
from flask import current_app, g, make_response, redirect, render_template, \
    request, url_for
from pygments import highlight
from pygments.formatters.html import HtmlFormatter
from pygments.lexers.data import JsonLexer

from app import db
from app.main import bp
from app.main.forms import SearchForm


TERM_BLACKLIST = ('http', 'com', 'bump', 'www')


class SuggestedTermFilter(xapian.ExpandDecider):
    def __call__(self, term):
        return term[:3] == b'ZXD'


@bp.before_app_request
def before_request():
    g.search_form = SearchForm()


@bp.route('/')
@bp.route('/index')
def index():
    # Return basic information about the collected threads/posts
    num_docs = db.get_doccount()

    return render_template(
        'index.html',
        num_docs=num_docs
    )


@bp.route('/docid/<int:docid>')
def get_doc_details(docid: int):
    doc: xapian.Document = db.get_document(docid)

    # Use pygments to pretty-print the json and use HTML5 code wrap
    html_formatter = HtmlFormatter(style='colorful', wrapcode=True)

    doc_ = dict(docid=docid,
                num_terms=doc.termlist_count(),
                json=highlight(doc.get_data().decode('utf-8'),
                               JsonLexer(), html_formatter),
                termlist=[term for term in doc],
                styles=html_formatter.get_style_defs()
                )
    return render_template('docid.html', doc=doc_)


@bp.route('/search')
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)

    # Build out our query and query
    queryparser = xapian.QueryParser()
    queryparser.set_stemmer(xapian.Stem('en'))
    queryparser.set_stemming_strategy(queryparser.STEM_SOME)
    queryparser.add_prefix('title', 'S')

    # Get the date range processing going
    queryparser.add_rangeprocessor(
        xapian.DateRangeProcessor(3, xapian.RP_DATE_PREFER_MDY)
    )

    phrase = g.search_form.phrase.data
    start_date = g.search_form.to.data
    end_date = g.search_form.from_.data

    _query = ''
    if start_date and end_date:
        _query += '{}..{}'.format(start_date, end_date)
    elif start_date and not end_date:
        _query += '{}..'.format(start_date)
    elif not start_date and end_date:
        _query += '..{}'.format(end_date)

    if _query and phrase:
        query = queryparser.parse_query('{} {}'.format(phrase, _query))
    else:
        query = queryparser.parse_query(g.search_form.phrase.data)

    enquire: xapian.Enquire = xapian.Enquire(db)
    enquire.set_query(query)
    matches: xapian.MSet = enquire.get_mset(
        (page - 1) * current_app.config['PAGE_SIZE'],
        current_app.config['PAGE_SIZE'])
    upper_bound: int = matches.get_matches_upper_bound()

    # Get some suggested terms
    rset = xapian.RSet()
    for match in enquire.get_mset(0, 10):
        rset.add_document(match.docid)
    eset = enquire.get_eset(20, rset, SuggestedTermFilter())
    temp_suggested_terms = set([res.term[3:].decode('utf-8') for res in eset])
    for search_term in query:
        temp_suggested_terms.add(search_term.decode('utf-8')[1:])
    temp_suggested_terms = [term for term in temp_suggested_terms if
                            term not in TERM_BLACKLIST and 'http' not in term]
    suggested_terms = list(temp_suggested_terms)[0:10]

    # Get some results
    parsed_matches = []
    match: xapian.MSetItem
    for match in matches:
        j = json.loads(match.document.get_data().decode('utf-8'))
        t = {
            'rank': match.rank,
            'percent': match.percent,
            # Generate a preview of the search term in the message text
            'snippet': matches.snippet(j['com']).decode('utf-8'),
            'date': datetime.fromtimestamp(j['time']).strftime('%Y-%m-%d'),
            'op': int(xapian.sortable_unserialise(match.document.get_value(1)))
        }
        parsed_matches.append(t)

    next_url = url_for('main.search',
                       phrase=g.search_form.phrase.data,
                       to=g.search_form.to.data,
                       from_=g.search_form.from_.data,
                       page=page + 1 if (page * current_app.config['PAGE_SIZE']) <= upper_bound else None)
    prev_url = url_for('main.search',
                       phrase=g.search_form.phrase.data,
                       to=g.search_form.to.data,
                       from_=g.search_form.from_.data,
                       page=page - 1)

    return render_template('search.html',
                           matches=parsed_matches,
                           next_url=next_url,
                           prev_url=prev_url,
                           to=g.search_form.to.data,
                           from_=g.search_form.from_.data,
                           suggested_terms=suggested_terms)


@bp.route('/thread/<int:thread>')
def op(thread: int):
    """
    Render a thread and its posts. The threads are set with a document slot
    whose value is the OP post number. In order to preserve the original thread
    ordering, the messages are sorted by the submission datetime
    :param thread: 4chan thread to be fetched
    :return:
    """
    queryparser: xapian.QueryParser = xapian.QueryParser()
    queryparser.add_prefix('thread', 'XOP')
    query: xapian.Query = queryparser.parse_query('thread:{}'.format(thread))

    enquire = xapian.Enquire(db)
    enquire.set_query(query)
    # Sort the posts by datetime posted descending
    enquire.set_sort_by_value(2, False)

    # It is unknown how many messages will be in a thread, but since there are
    # limits on the number of posts allowed, just load them all.
    matches: xapian.MSet = enquire.get_mset(0, db.get_doccount())
    match: xapian.MSetItem
    match_data = []
    for match in matches:
        post = json.loads(match.document.get_data().decode('utf-8'))
        # The time attribute in the post is epoch, but since we'll use the
        # HTML5 <time> element, convert to the equivalent UTC timestamp
        post['datetime'] = datetime.fromtimestamp(post['time']).strftime("%Y-%m-%d %H:%M:%S.%fZ")
        post['docid'] = match.docid
        match_data.append(post)
    return render_template('_thread.html', thread=match_data)

app/templates/_thread.html
{% extends "base.html" %}

{% block app_content %}
<h1>{{ thread[0]['sub'] }}</h1>
<table id="threadtable" class="table">
    <thead>
    <tr>
        <th>Message ID</th>
        <th>Date Sent</th>
        <th>Trip Code</th>
        <th>Poster</th>
        <th>Message</th>
    </tr>
    </thead>
    {% for post in thread %}
    <tr id="p{{ post['no'] }}">
        <td><a href="{{ url_for('main.get_doc_details', docid=post['docid']) }}">{{ post['no'] }}</a></td>
        <td>
            <time datetime="{{ post['datetime'] }}">{{ post['datetime'] }}</time>
        </td>
        <td>{{ post['trip'] }}</td>
        <td>{{ post['name'] }}</td>
        <td>{{ post['com'] | safe }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    Welcome to changine
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-headers">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">changine</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="navbar navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.search') }}">Test</a></li>
                </ul>
                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
                    <div class="form-group">
                        {{ g.search_form.phrase(size=50, class='form-control', placeholder=g.search_form.phrase.label.text) }}
                        {{ g.search_form.to }}
                        {{ g.search_form.from_ }}
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
<div class="container">
{% block app_content %}{% endblock %}
</div>
{% endblock %}

app/templates/docid.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<style>{{ doc.styles }}</style>
{% endblock %}
{% block app_content %}
<ul>
    <li>docid: {{ doc['docid'] }}</li>
    <li>number of terms: {{ doc['num_terms'] }}</li>
    <li>term list: {% for term in doc['termlist'] %}{{ term.term.decode('utf-8') }}{% endfor %}</li>
    <li>docdata: {{ doc.json|safe}}</li>
</ul>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Welcome to changine</h1>
<h2>database statistics</h2>
number of documents = {{ num_docs }}<br><br>
<a href="/search">Get started searching!</a><br><br>
This database was made possible by the <a href="https://zenodo.org/record/3606810">data</a> collected for the
<a href="https://arxiv.org/abs/2001.07487">Raiders of the Lost Kek</a> paper.<br>
It encompasses 3.5 years of 4chan /pol/ posts with approximately 3.3M threads and 135M messages.
{% endblock %}

app/templates/results.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Search Results</h1>
{% if matches %}
<br>
Additional suggested terms: {% for term in suggested_terms %}{{ term+'\t' }} {% endfor %}
<table class="table table-hover">
    <thead>
    <tr>
        <th>Rank</th>
        <th>Percent Match</th>
        <th>Date</th>
        <th>snippet</th>
        <th>thread</th>
    </tr>
    </thead>
    {% for match in matches %}
    {# `match` is a MSetItem object #}
    <tr>
        <td>{{ match.rank + 1 }}</td>
        <td>{{ match.percent }}</td>
        <td>{{ match.date }}</td>
        <td>{{ match.snippet|safe }}</td>
        <td><a href="{{ url_for('main.op', thread=match.op) }}">{{ match.op }}</a></td>
    </tr>
    {% endfor %}
</table>
<nav aria-label="pagination">
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="{{ url_for('main.results', page=1, query=query) }}">First Page</a></li>
        {% if prev_url %}
        <li class="page-item"><a class="page-link" href="{{ prev_url }}">Previous</a></li>
        {% endif %}
        {% if next_url %}
        <li class="page-item"><a class="page-link" href="{{ next_url }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
<a href="{{ url_for('main.search') }}">Back to Search</a>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
Additional suggested terms: {% for term in suggested_terms %}{{ term+'\t' }} {% endfor %}
<table class="table table-hover">
    <thead>
    <tr>
        <th>Rank</th>
        <th>Percent Match</th>
        <th>Date</th>
        <th>Preview</th>
        <th>Thread</th>
    </tr>
    </thead>
    {% for match in matches %}
    {# `match` is a MSetItem object #}
    <tr>
        <td>{{ match.rank + 1 }}</td>
        <td>{{ match.percent }}</td>
        <td>{{ match.date }}</td>
        <td>{{ match.snippet|safe }}</td>
        <td><a href="{{ url_for('main.op', thread=match.op) }}">{{ match.op }}</a></td>
    </tr>
    {% endfor %}
</table>
<nav aria-label="pagination">
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="{{ url_for('main.search', page=1, phrase=phrase, to=to, from_=from_) }}">First Page</a></li>
        {% if prev_url %}
        <li class="page-item"><a class="page-link" href="{{ prev_url }}">Previous</a></li>
        {% endif %}
        {% if next_url %}
        <li class="page-item"><a class="page-link" href="{{ next_url }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}